Update protobuf-c.spec
daos-stack/protobuf-c pull request #8
Opened 2021-01-16 10:03 UTC by tanabarr

Bump version to 1.3.3 to reflect the version that developers are using in DAOS.

2021-01-18 21:19 UTC, brianjmurrell requested changes
You need to update the [packaging/](https://github.com/daos-stack/protobuf-c/tree/9e2246cf8f4fa19d3d1a68bf9a98103bfafc0167/packaging) directory to what's currently in [daos-stack/packaging](https://github.com/daos-stack/packaging/).  The easiest way to do that is to check out [daos-stack/packaging](https://github.com/daos-stack/packaging/)'s master somewhere and then while in your protobuf-c clone (i.e. this PR)'s root directory run `$path-to-packaging-repo-checkout/install`.

There is potential to automate this updating at some point in the future with GitHub actions, but for now, it's manual.

2021-01-19 15:17 UTC, tanabarr commented
I received a packaging is out of date e-mail but I've updated as you instructed with recent master (I think)

2021-01-19 16:23 UTC, brianjmurrell requested changes
Looks good @tanabarr.  You just have one small `packaging/` issue to resolve per https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fprotobuf-c/detail/PR-8/2/pipeline/30:

```
[2021-01-19T15:15:53.950Z] Only in packaging/: Dockerfile.ubuntu.18.04
```

That means that you need to `git rm packaging/Dockerfile.ubuntu.18.04`.  This is because we have moved to Ubuntu 20.04 since this module was last updated.

2021-01-19 20:14 UTC, brianjmurrell approved these changes

2021-01-20 12:56 UTC, merged